<!-- 4. OSU Black Banner w/ Orange Narrow Divider & Utility Links -->
<div id="tb_banner">
    <div id="tb_bannerUtility">
        <a href="#content"><img src="http://oregonstate.edu/u_central/images/blackHeight.gif" alt="skip page navigation" width="13" height="42" border="0" /></a><a href="http://oregonstate.edu" target="_parent"><img src="http://oregonstate.edu/u_central/images/blackWordmark.gif" alt="Oregon State University" width="262" height="42" border="0" /></a>
    </div>

    <div id="tb_utility">
        <a href="http://oregonstate.edu" target="_parent"><img src="http://oregonstate.edu/u_central/images/b_osuHome.gif" width="66" height="14" border="0" alt="OSU Home" /></a>
        <a href="http://calendar.oregonstate.edu/"><img src="http://oregonstate.edu/u_central/images/b_calendar.gif" width="55" height="14" border="0" alt="Calendar" /></a>
        <a href="http://oregonstate.edu/findsomeone/"><img src="http://oregonstate.edu/u_central/images/b_findsomeone.gif" width="82" height="14" border="0" alt="Find Someone" /></a>
        <a href="http://oregonstate.edu/cw_tools/campusmap/"><img src="http://oregonstate.edu/u_central/images/b_maps.gif" width="37" height="14" border="0" alt="Maps" /></a>
        <a href="http://oregonstate.edu/siteindex.html"><img src="http://oregonstate.edu/u_central/images/b_siteIndex.gif" width="49" height="14" border="0" alt="Site Index" /></a>
    </div>
</div>

