<!-- nav bar -->

<br/>
<center><img src="http://oregonstate.edu/net/images/milne.jpg"></center>
<br />

<center>
<a href="http://oregonstate.edu/net/">Home</a><br/>    
<a href="http://oregonstate.edu/net/info/status/">Status</a><br/>
<a href="http://oregonstate.edu/net/network/">Network Info</a><br/>

<a href="http://oregonstate.edu/net/security/">Security</a><br/>
<a href="http://oregonstate.edu/net/services/">Services</a><br/>
<a href="http://oregonstate.edu/net/info/dca/admins.php">DCA Resources</a><br/>
<a href="http://oregonstate.edu/net/info/">Docs/Policy</a><br/>
<a href="http://oregonstate.edu/net/gallery/">Gallery</a><br/>
<a href="http://oregonstate.edu/net/blog/">NET Blog</a><br/>

<a href="http://oregonstate.edu/net/info/sitemap.php">Site Map</a><br/>
<a href="http://oregonstate.edu/net/contact/">Contact Us</a><br/>
</center>

<br/>

<!-- osu search -->
<form name="gs" method="get" action="http://search.oregonstate.edu/web" style="align:center;">
    <table>

        <tfoot>
            <tr><td>
                <center>
                <label for="site"><input type="checkbox" id="site" name="site" value="oregonstate.edu/net" checked="checked" />Search this site only.</label>
                </center>
            </td></tr>
        </tfoot>

        <tbody>
            <tr><td>
                <center>
                <label for="query" title="Enter your search query here.">

                    <input type="text" id="query" name="query" size="14" maxlength="256" value="Search OSU!" accesskey="s" onfocus="select(this);value='';" onblur="if(value==''){value='Search OSU!';}" />
                </label>
                <input type="submit" value="Go" title="Search OSU." />
                </center>
            </td></tr>
        </tbody>

    </table>
</form>
<!-- end osu search -->

<center>
Oregon State University<br />
Kerr Admin B211<br / >
Corvallis, OR 97331<br />
</center>

<center><br />
    <p><a target="_blank" href="http://www.abilene.iu.edu"><img src="http://oregonstate.edu/net/images/abilene.gif" alt="Abilene" border="0"></a></p><br />

    <p><a target="_blank" href="http://www.internet2.edu"><img src="http://oregonstate.edu/net/images/i2.gif" alt="Internet2 Member" border="0"></a></p>
</center>

<br/>
<!-- end nav bar -->
